DefaultContentLanguage = "hr"
baseURL = "/"
title = "UBIK | Udruga za blockchain i kriptovalute"

######################## default configuration ####################
theme = "educenter-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
#disqusShortname = "educenter" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ["en"]

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"

#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
author = "UBIK"
description = "Zajednica ljudi uključena u blockchain i kripto domenu u Hrvatskoj i regiji."
# contact info
ubik = "Udruga za blockchain i kriptovalute - UBIK"
address = "Medulićeva 4, 10000 Zagreb, Hrvatska"
email = "Email: info@ubik.hr"
phone = "Kontakt telefon: 01/4106-456"
oib = "49493768738"
regbr = "Registarski broj: 21012855"
account = "Transakcijski račun: HR0324020061100858697"
# contact form action
contact_form_action = "https://formspree.io/f/mjvpjgyj" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = false

# Preloader
[params.preloader]
enable = true 
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://ubik.us17.list-manage.com/subscribe/post" 
mailchimp_id = "a28ed76483" 
mailchimpuser = "" ## Overridden by env variable

# cookies
[params.cookies]
enable = false
expire_days = 30

############################# social site ########################
[[params.social]]
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/UBIK.hr" 
title = "facebook" 

[[params.social]]
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/ubikhr" 
title = "twitter" 

[[params.social]]
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/ubikhr" 
title = "github" 

[[params.social]]
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/ubik-udruga-za-blockchain-i-kriptovalute/" 
title = "linkedin" 

[[params.social]]
icon = "ti-youtube" # themify icon : https://themify.me/themify-icons
link = "https://www.youtube.com/channel/UCkGBfraJol0oLQEYmkxb_ug" 
title = "youtube"

[[params.social]]
icon = "/icons/icons8-telegram-app.svg" # icons8 icon : https://icons8.com/icons/set/telegram
link = "https://t.me/ubikcommunity"
title = "telegram"

################################### English language #####################################
[Languages.en]
contentDir = "content/english"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 2

################### English navigation ####################

# main menu
[[Languages.en.menu.main]]
name = "blog"
url = "blog"
weight = 2

[[Languages.en.menu.main]]
name = "members"
url = "members"
weight = 2

[[Languages.en.menu.main]]
name = "Forum"
url = "https://forum.ubik.hr"
weight = 3

[[Languages.en.menu.main]]
name = "Contact"
url = "contact"
weight = 4

################################### Croatian language #####################################
[Languages.hr]
contentDir = "content/english"
home = "Početna"
languageCode = "hr"
languageName = "Hr"
weight = 1

################### Croatian navigation ####################

# main menu
[[Languages.hr.menu.main]]
name = "blog"
url = "blog"
weight = 2

[[Languages.hr.menu.main]]
name = "članovi"
url = "members"
weight = 2

[[Languages.hr.menu.main]]
name = "Forum"
url = "https://forum.ubik.hr"
weight = 3

[[Languages.hr.menu.main]]
name = "kontakt"
url = "contact"
weight = 4


[markup.goldmark.renderer]
unsafe = true
