name: Issue notification

on:
  issues:
    types: [opened, closed, edited]

jobs:
  notify:
    name: Notify about issue changes
    runs-on: ubuntu-latest
    steps:
      - name: Send TG message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          
          message:
            UBIKhr/web [issue \#${{ github.event.issue.number }}](https://github.com/UBIKhr/web/issue/${{ github.event.issue.number }}) ${{ github.event.event_name }}.
    