name: Page Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # Fetch Hugo themes
          fetch-depth: 0   # Fetch all history for .GitInfo and .Lastmod

      - uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive --ignore-optional --network-timeout 600000
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Build
        run: yarn build
        env:
          NODE_OPTIONS: --openssl-legacy-provider
          HUGO_PARAMS_SUBSCRIPTION_mailchimpuser: ${{ secrets.HUGO_PARAMS_MAILCHIMP_U }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
          clean: true

      - name: Notify deployment
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message:
            Blog je ažuriran. [Vidi promjene](https://github.com/UBIKhr/web/commit/${{ github.sha }}).
